In [1]:
%matplotlib
import numpy as np
import pandas as pd
import statsmodels.api as sm
import math

Using matplotlib backend: MacOSX


# Load in training and test data

In [103]:
sales_train = pd.read_csv('kc_house_train_data.csv')
sales_test = pd.read_csv('kc_house_test_data.csv')

## Add more features

In [3]:
sales_train['bedrooms_squared'] = sales_train['bedrooms']**2
sales_train['bed_bath_rooms'] = sales_train['bedrooms']*sales_train['bathrooms']
sales_train['log_sqft_living'] = np.log(sales_train['sqft_living'])
sales_train['lat_plus_long'] = sales_train['lat'] + sales_train['long']
sales_test['bedrooms_squared'] = sales_test['bedrooms']**2
sales_test['bed_bath_rooms'] = sales_test['bedrooms']*sales_test['bathrooms']
sales_test['log_sqft_living'] = np.log(sales_test['sqft_living'])
sales_test['lat_plus_long'] = sales_test['lat'] + sales_test['long']

In [14]:
sales_train[:3]

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   

   sqft_lot  floors  waterfront  view        ...         zipcode      lat  \
0      5650     1.0           0     0        ...           98178  47.5112   
1      7242     2.0           0     0        ...           98125  47.7210   
2     10000     1.0           0     0        ...           98028  47.7379   

      long  sqft_living15  sqft_lot15  bedrooms_squred  bed_bath_rooms  \
0 -122.257           1340        5650                9            3.00   
1 -122.319           1690        7639                9            6.75   
2 -122.233           2720        8062                4            2.00   

   log_sqft_living  lat_plus_long  bedrooms_squared  
0         7.073270       -74.7458                 9  
1         7.851661       -74.5980                 9  
2         6.646391       -74.4951                 4  

[3 rows x 26 columns]

In [15]:
print sales_test['bedrooms_squared'].mean()
print sales_test['bed_bath_rooms'].mean()
print sales_test['log_sqft_living'].mean()
print sales_test['lat_plus_long'].mean()

12.4466777016
7.50390163159
7.55027467965
-74.653333554


# Simple Regression Model

In [29]:
X1 = sales_train[['sqft_living', 'bedrooms', 'bathrooms', 'lat','long']]
X1 = sm.add_constant(X1)
model1 = sm.OLS(sales_train['price'],X1)

In [30]:
model1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.592
Method:                 Least Squares   F-statistic:                     5056.
Date:                Wed, 29 Jun 2016   Prob (F-statistic):               0.00
Time:                        12:35:18   Log-Likelihood:            -2.3973e+05
No. Observations:               17384   AIC:                         4.795e+05
Df Residuals:                   17378   BIC:                         4.795e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P>|t|      [95.0% Conf. Int.]
-------------------------------------------------------------------------------
const       -6.908e+07   1.65e+06    -41.940      0.000     -7.23e+07 -6.58e+07
sqft_living   312.2586      3.183     98.097      0.000       306.019   318.498
bedrooms    -5.959e+04   2482.861    -23.999      0.000     -6.45e+04 -5.47e+04
bathrooms    1.571e+04   3587.158      4.379      0.000      8675.552  2.27e+04
lat          6.586e+05   1.31e+04     50.286      0.000      6.33e+05  6.84e+05
long        -3.094e+05   1.33e+04    -23.331      0.000     -3.35e+05 -2.83e+05
==============================================================================
Omnibus:                    12962.917   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           615844.364
Skew:                           3.114   Prob(JB):                         0.00
Kurtosis:                      31.486   Cond. No.                     2.10e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.1e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [37]:
X2 = sales_train[['sqft_living', 'bedrooms', 'bathrooms', 'lat','long','bed_bath_rooms']]
X2 = sm.add_constant(X2)
model2 = sm.OLS(sales_train['price'],X2)

In [28]:
model2.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.597
Model:                            OLS   Adj. R-squared:                  0.596
Method:                 Least Squares   F-statistic:                     4283.
Date:                Wed, 29 Jun 2016   Prob (F-statistic):               0.00
Time:                        12:34:48   Log-Likelihood:            -2.3965e+05
No. Observations:               17384   AIC:                         4.793e+05
Df Residuals:                   17377   BIC:                         4.794e+05
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==================================================================================
                     coef    std err          t      P>|t|      [95.0% Conf. Int.]
----------------------------------------------------------------------------------
const          -6.687e+07   1.65e+06    -40.584      0.000     -7.01e+07 -6.36e+07
sqft_living      306.6101      3.197     95.909      0.000       300.344   312.876
bedrooms       -1.134e+05   4797.612    -23.646      0.000     -1.23e+05 -1.04e+05
bathrooms      -7.146e+04   7552.563     -9.462      0.000     -8.63e+04 -5.67e+04
lat             6.548e+05    1.3e+04     50.230      0.000      6.29e+05   6.8e+05
long           -2.943e+05   1.32e+04    -22.218      0.000      -3.2e+05 -2.68e+05
bed_bath_rooms  2.558e+04   1953.134     13.097      0.000      2.18e+04  2.94e+04
==============================================================================
Omnibus:                    12343.124   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           533516.100
Skew:                           2.916   Prob(JB):                         0.00
Kurtosis:                      29.506   Cond. No.                     2.11e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.11e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
X3 = sales_train[['sqft_living', 'bedrooms', 'bathrooms', 'lat','long','bed_bath_rooms','bedrooms_squared','log_sqft_living','lat_plus_long']]
X3 = sm.add_constant(X3)
model3 = sm.OLS(sales_train['price'],X3)

In [32]:
model3.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.620
Model:                            OLS   Adj. R-squared:                  0.620
Method:                 Least Squares   F-statistic:                     3539.
Date:                Wed, 29 Jun 2016   Prob (F-statistic):               0.00
Time:                        12:35:50   Log-Likelihood:            -2.3913e+05
No. Observations:               17384   AIC:                         4.783e+05
Df Residuals:                   17375   BIC:                         4.784e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------------
const            -6.204e+07   1.61e+06    -38.449      0.000     -6.52e+07 -5.89e+07
sqft_living        529.4228      7.691     68.836      0.000       514.348   544.498
bedrooms          3.451e+04   9385.891      3.677      0.000      1.61e+04  5.29e+04
bathrooms         6.706e+04   1.08e+04      6.219      0.000      4.59e+04  8.82e+04
lat               5.341e+05   8907.125     59.962      0.000      5.17e+05  5.52e+05
long             -4.068e+05   9007.995    -45.154      0.000     -4.24e+05 -3.89e+05
bed_bath_rooms   -8570.5044   2855.965     -3.001      0.003     -1.42e+04 -2972.526
bedrooms_squared -6788.5867   1493.406     -4.546      0.000     -9715.813 -3861.360
log_sqft_living  -5.618e+05   1.75e+04    -32.014      0.000     -5.96e+05 -5.27e+05
lat_plus_long     1.273e+05   6450.344     19.741      0.000      1.15e+05   1.4e+05
==============================================================================
Omnibus:                    10094.582   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           319322.176
Skew:                           2.240   Prob(JB):                         0.00
Kurtosis:                      23.513   Cond. No.                     5.53e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.96e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [33]:
print model1.fit().ssr
print model2.fit().ssr
print model3.fit().ssr

9.6787996305e+14
9.58419635074e+14
9.0343645505e+14


In [41]:
def get_residual_sum_of_squares(model,features,y):
    predicted = model.fit().predict(sm.add_constant(features))
    return np.power((predicted - y),2).sum(axis=0)

In [46]:
print get_residual_sum_of_squares(model1,sales_test[['sqft_living', 'bedrooms', 'bathrooms', 'lat','long']],sales_test['price'])
print get_residual_sum_of_squares(model2,sales_test[['sqft_living', 'bedrooms', 'bathrooms', 'lat','long','bed_bath_rooms']],sales_test['price'])
print get_residual_sum_of_squares(model3,sales_test[['sqft_living', 'bedrooms', 'bathrooms', 'lat','long','bed_bath_rooms','bedrooms_squared','log_sqft_living','lat_plus_long']],sales_test['price'])

2.25500469795e+14
2.23377462976e+14
2.59236319207e+14


# Assignment #2 - Using Gradient Descent

In [7]:
len(sales_test)
sales_train.as_matrix(['sqft_living'])
np.ones((len(sales_train),1))

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 1.],
       [ 1.],
       [ 1.]])

In [12]:
def get_numpy_data(data,features,output):
    constant_col = np.ones((len(data),1))
    features_matrix = np.hstack((constant_col, data.as_matrix(features)))
    output_array = data.as_matrix([output])
    return (features_matrix, output_array)

In [57]:
simple_feature = ['sqft_living']
output_var ='price'
(simple_feature_matrix, output) = get_numpy_data(sales_train,simple_feature,output_var)
init_weights = [-47000., 1.]
print np.dot(simple_feature_matrix,init_weights).reshape((-1,1))
print output
print simple_feature_matrix[:,0]
print (output - predict_outcome(simple_feature_matrix,init_weights))
print np.dot(simple_feature_matrix[:,0],(output - predict_outcome(simple_feature_matrix,init_weights)))

[[-45820.]
 [-44430.]
 [-46230.]
 ..., 
 [-45470.]
 [-45400.]
 [-45980.]]
[[ 221900.]
 [ 538000.]
 [ 180000.]
 ..., 
 [ 360000.]
 [ 400000.]
 [ 325000.]]
[ 1.  1.  1. ...,  1.  1.  1.]
[[ 267720.]
 [ 582430.]
 [ 226230.]
 ..., 
 [ 405470.]
 [ 445400.]
 [ 370980.]]
[  1.01572382e+10]


In [52]:
def predict_outcome(features_matrix,weight):
    return np.dot(features_matrix,weight).reshape((-1,1))

In [59]:
def feature_derivative(feature, errors):
    return -2*np.dot(feature, errors)

In [61]:
def regression_gradient_descent(feature_matrix,output_array,initial_weights,step_size,tolerance):
    converged = False
    weights = np.array(initial_weights)
    while not converged:
        # compute the predictions based on feature_matrix and weights:
        predictions = predict_outcome(feature_matrix,weights)
        # compute the errors as predictions - output:
        error = output - predictions
        # initialize gradient
        gradient_sum_sq = 0
        # step through each feature and update weight
        for i in range(len(weights)):
            feature_i_derivative = feature_derivative(feature_matrix[:,i],error)
            gradient_sum_sq += feature_i_derivative**2
            weights[i] -= step_size * feature_i_derivative
        gradient_magnitude = math.sqrt(gradient_sum_sq)
        if gradient_magnitude < tolerance:
            converged = True 
    return weights

# Use Gradient Descent to make predictions

In [112]:
simple_feature = ['sqft_living']
output_var ='price'
(simple_feature_matrix, output) = get_numpy_data(sales_train,simple_feature,output_var)
init_weights = [-47000., 1.]
step_size = 7e-12
tolerance = 2.5e7

In [113]:
simple_weights = regression_gradient_descent(simple_feature_matrix,output,init_weights,step_size,tolerance)

In [114]:
print simple_weights

[-46999.88716555    281.91211918]


# Make predictions

In [115]:
(test_simple_feature_matrix,test_output) = get_numpy_data(sales_test,simple_feature,output_var)
print test_output

[[ 310000.]
 [ 650000.]
 [ 233000.]
 ..., 
 [ 610685.]
 [ 400000.]
 [ 402101.]]


In [116]:
predictions_test = predict_outcome(test_simple_feature_matrix,simple_weights)
print predictions_test

[[ 356134.443255  ]
 [ 784640.86440132]
 [ 435069.83662406]
 ..., 
 [ 663418.65315598]
 [ 604217.10812919]
 [ 240550.47439317]]


In [117]:
rss = ((test_output - predictions_test)**2).sum()
print rss

2.75400044902e+14


# Using two features to make predictions

In [125]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix, output) = get_numpy_data(sales_train, model_features,my_output)
weights = [-100000., 1., 1.]
step_size = 4e-12
tolerance = 1e9
print output

[[ 221900.]
 [ 538000.]
 [ 180000.]
 ..., 
 [ 360000.]
 [ 400000.]
 [ 325000.]]


In [123]:
model_weights = regression_gradient_descent(feature_matrix,output,weights,step_size,tolerance)

In [120]:
print model_weights
print weights

[ -9.99999688e+04   2.45072603e+02   6.52795267e+01]
[-100000.0, 1.0, 1.0]


In [132]:
(test_model_feature_matrix,test_output) = get_numpy_data(sales_test,model_features,my_output)
predictions_test2 = predict_outcome(test_model_feature_matrix,model_weights)
print predictions_test2

[[ 366651.41162949]
 [ 762662.39850726]
 [ 386312.09557541]
 ..., 
 [ 682087.39916306]
 [ 585579.27901327]
 [ 216559.20391786]]


In [135]:
rss_model = ((test_output - predictions_test2)**2).sum()
print rss_model

2.7026344363e+14
